#!/bin/zsh

# Runs on login
# Stores environment variable

# Setup homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# Setup thefuck
eval $(thefuck --alias)

# Adds `~/.local/bin` to $PATH
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
export PATH="$PATH:$(yarn global bin)"

# Source tmux bins
export PATH=$HOME/.config/tmux/plugins/t-smart-tmux-session-manager/bin:$PATH

# Angular Autocomplete
source <(ng completion script)

# Default programs:
export EDITOR="nvim"
# export TERMINAL="st"
# export TERMINAL_PROG="st"
export BROWSER="firefox"

# Home directory clean up
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export NVM_DIR="$HOME/.local/bin/nvm"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"

[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && setsid shortcuts >/dev/null 2>&1


# Setup nvm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# Start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"

# if [ "$TMUX" = "" ]; then tmux; fi
# if [ -z "$TMUX" ]; then tmux attach -t TMUX || tmux new -s TMUX; fi
# [ -x "$(command -v xinit)" ] &&  [ "$(tty)" = "/dev/tty1" ] & ! pidof -s Xorg >/dev/null 2>&1 && exec startx $XINITRC"
