#!/bin/zsh

# Runs on login
# Stores environment variable

# Default programs:
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="brave"

# Home directory clean up
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && setsid shortcuts >/dev/null 2>&1

# Adds `~/.local/bin` to $PATH
if [ "$(uname)" != "Darwin" ]; then
  export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
fi

# Start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && [ -x "$(command -v Hyprland)" ] && ! pidof -s Hyprland >/dev/null 2>&1 && exec Hyprland
